version: '3.8'
services:
  mysql-container:
    image: mysql:8
    container_name: pet_clinic_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet_clinic_rs
    ports:
      - 3307:3306
    restart: always
    volumes:
      - db:/var/lib/mysql
  angular-container:
    container_name: pet_clinic_angular
    image: gala107/pet_clinic_angular:1.0
    ports:
      - 85:80
    restart: always  
  springboot-container:
    container_name: pet_clinic_sboot 
    image: gala107/pet_clinic_sboot:1.0
    depends_on:
      - mysql-container
    ports:
      - 8282:8282
    restart: always
volumes:
  db:
   driver: local 